SPECTRAL_COLUMNS = [
    "f",
    "df",
    "a1",
    "b1",
    "a2",
    "b2",
    "varianceDensity",
    "direction",
    "directionalSpread",
]


COLUMN_MAP = {
    "Battery Voltage (V)": "batteryVoltage",
    "Power (W)": "power",
    "Humidity (%rel)": "humidity",
    "Epoch Time": "time",
    "Significant Wave Height (m)": "significantWaveHeight",
    "Peak Period (s)": "peakPeriod",
    "Mean Period (s)": "meanPeriod",
    "Peak Direction (deg)": "peakDirection",
    "Peak Directional Spread (deg)": "peakDirectionalSpread",
    "Mean Direction (deg)": "meanDirection",
    "Mean Directional Spread (deg)": "meanDirectionalSpread",
    "Latitude (deg)": "latitude",
    "Longitude (deg)": "longitude",
    "f": "frequency",
    "df": "frequencyBandwidth",
    "a1": "a1",
    "b1": "b1",
    "a2": "a2",
    "b2": "b2",
    "varianceDensity": "varianceDensity",
    "direction": "direction",
    "directionalSpread": "directionalSpread",
    "Wind Speed (m/s)": "windSpeed",
    "Wind Direction (deg)": "windDirection",
    "Surface Temperature (°C)": "surfaceTemperature",
    "Partition0 Start Frequency (hz)": "partition0StartFrequency",
    "Partition0 End Frequency (hz)": "partition0EndFrequency",
    "Partition0 Significant Wave Height (m)": "partition0SignificantWaveHeight",
    "Partition0 Mean Period (s)": "partition0MeanPeriod",
    "Partition0 Mean Direction (deg)": "partition0MeanDirection",
    "Partition0 Mean Directional Spread (deg)": "partition0MeanDirectionalSpread",
    "Partition1 Start Frequency (hz)": "partition1StartFrequency",
    "Partition1 End Frequency (hz)": "partition1EndFrequency",
    "Partition1 Significant Wave Height (m)": "partition1SignificantWaveHeight",
    "Partition1 Mean Period (s)": "partition1MeanPeriod",
    "Partition1 Mean Direction (deg)": "partition1MeanDirection",
    "Partition1 Mean Directional Spread (deg)": "partition1MeanDirectionalSpread",
    "Mean Barometric Pressure (hPa)": "meanBarometricPressure",
    "Processing Source": "processingSource",
}
